# 📊 Introduction to NumPy Arrays
NumPy arrays are the foundation of numerical computing in Numpy. They are more efficient and fast than Python lists and support powerful operations for data manipulation.
They are often called vector in vectorial math

They also have some key limits:
    
    - Fixed Lenght, you cannot change the their lenght (like other languages)
    
    - They can contain a single type of data type for efficiency reasons 
    
    - They can contain other arrays within and in this way they can aquire new dimensions, 2d arrays are called matrixes and arrays with two or more dimensions are called tensors

    - They must have values inside them inizialized at some value they cannot contain none


## How create a simple array? 

In [ ]:
import numpy as np

arr = np.array([1,2,3,4,5,6]) # array creation
print(arr)

[1 2 3 4 5 6]


## Accessing Elements with slicing

We can access element or elements of the array using the wanted index inside square brackets 

In [ ]:
print(arr[0])
print(arr[1:-1])
arr[0] = 222  # updating an element
print(arr)


1
[2 3 4 5]
[222   2   3   4   5   6]


## Multidimensional Arrays

Arrays can contain other arrays, which may themselves contain other arrays, and so on — potentially endlessly. Each level of nesting introduces a new dimension called axis or rank, allowing us to represent increasingly complex structures.
Different rank arrays are used for representing different type of things in data science :

- A 1D array is like a simple list: a sequence of values.
- A 2D array is like a matrix: rows and columns, they are called for this reason "matrix".
- A 3D array adds depth: imagine a stack of matrices, when rank is 3 or more they are called "tensors".
- Higher dimensions (4D, 5D, etc.) are used in advanced applications like image processing, scientific simulations, and machine learning



## Creating a Matrix and a Tensor with a specified data type

In [ ]:
matrix = np.array([   #2d
    [22,33,44],
    [55,88,99],
    [99,444,444]
], dtype=str) #  We are specifying wich data type we want the array to contain

tensor = np.array([matrix, matrix, matrix])  #3d

print("-----This is a 2d array----------\n",matrix)

print("\n-------This is a 3d array-------\n", tensor)

-----This is a 2d array----------
 [['22' '33' '44']
 ['55' '88' '99']
 ['99' '444' '444']]

-------This is a 3d array-------
 [[['22' '33' '44']
  ['55' '88' '99']
  ['99' '444' '444']]

 [['22' '33' '44']
  ['55' '88' '99']
  ['99' '444' '444']]]


## Accessing elements in the Tensor and the Matrix

In [21]:
print("Element at -y : 1, -x : 0 of the Matrix ", matrix[1][0]) # Second list , first index 

print("Element at -z : 1 , y : 2, x : 3 of the Tensor", tensor[0][1][2])  # First Matrix , second list , second index

Element at -y : 1, -x : 0 of the Matrix  55
Element at -z : 1 , y : 2, x : 3 of the Tensor 99


## Accessing to size and dimensions of array , matrices and tensors, and the data type it contains

In [ ]:
print("Array lenght : ", len(arr)) # show the most outer dimension, indexing can be used to go deeper in case of multiple dimensions
print("Tensor dimensions : ", tensor.shape) # retrned in a tuple from the most outer in this case : z x y 
print("Tensor total number of element : ", tensor.size) # shows how many single elements are in the tensor
print("Number of dimensions of the tensor : ",  tensor.ndim) # shows how many dimensions has the tensor
print("Data type of the matrix :", matrix.dtype) # show the datatype of the matrix

Array lenght :  6
Tensor dimensions :  (2, 3, 3)
Tensor total number of element :  18
Number of dimensions of the tensor :  3
Data type of the matrix : <U3
