# Matrix Decomposition: What Does It Mean?

Decomposing a matrix means representing it as the product of simpler matrices.  
This is analogous to integer factorization (for example, 12 = 3 × 4).  
Similarly, a matrix **A** can be factored into simpler matrices which, when multiplied together,  
reconstruct **A**.

## Why Use Decomposition?

- **Reduces computational cost**  
- **Improves numerical stability** in calculations  
- **Enables complex problems** to be solved more efficiently

#### LU Decomposition

**Definition**  
LU decomposition factors a square matrix **A** into the product of two matrices:

- **L** → Lower triangular matrix (with 1s on the diagonal)  
- **U** → Upper triangular matrix

**Purpose**  
- Solve systems of linear equations efficiently  
- Avoid computing the inverse of a matrix directly  
- Improve numerical stability in some algorithms  
- Quickly compute determinants (as the product of diagonal entries of **U**)

**Key Points**  
- Works best for **non-singular** square matrices  
- Sometimes combined with a permutation matrix **P** for pivoting (see LUP decomposition)  
- The process is based on Gaussian elimination

#### Matrix Decomposition: LUP Decomposition

**Definition**  
Let **A** be an invertible matrix. Then **A** can be decomposed as:  
- **P** → a permutation matrix  
- **L** → a lower triangular matrix  
- **U** → an upper triangular matrix  

**Explanation**  
During the decomposition, the rows of the original matrix are rearranged to simplify calculations.  
The permutation matrix **P** is used to indicate how to permute the results and, if needed, return them to the original order.

A **permutation matrix** (or permutational matrix) is obtained by swapping certain rows or columns of the identity matrix.

In [5]:
"""
Lup Deomposition
"""
import numpy as np
from scipy.linalg import lu

# Example matrix
A = np.array([[1, 3], [3, 4]])


P , L , U = lu(A)
print("Lower Triangular :\n", L )
print("Upper Triangular :\n", U )
print("Permutation matrix : \n", P)

print ("Original matrix A :\n" , P @ L @ U) # The order is fixed inverting this order will not get you the original matrix

Lower Triangular :
 [[1.         0.        ]
 [0.33333333 1.        ]]
Upper Triangular :
 [[3.         4.        ]
 [0.         1.66666667]]
Permutation matrix : 
 [[0. 1.]
 [1. 0.]]
Original matrix A :
 [[1. 3.]
 [3. 4.]]


# QR Decomposition: Orthogonal Matrix

**Definition**  
An orthogonal matrix **Q** is a square matrix that satisfies the following fundamental conditions:

**Properties**  
- The rows and columns of **Q** are **orthonormal vectors** (i.e., mutually perpendicular and of unit length).  
- The inverse of **Q** equals its transpose:  
- Multiplication by **Q** preserves lengths and angles: it does **not** scale or distort vectors, but can rotate or reflect them.

**Example**  
A **rotation matrix** is an example of an orthogonal matrix.

In [ ]:
# Example matrix (3x2)
A = np.array([[1, 2],
              [3, 4],
              [5, 6]])

# Perform QR decomposition - complete mode (Q is m x m)
Q, R = np.linalg.qr(A, mode='complete')

print("Orthogonal matrix Q (m x m):\n", Q)
print("\nUpper triangular matrix R (m x n):\n", R)

# Cholesky Decomposition

**Definition**  
The Cholesky can be used on a **symmetric,square, positive-definite** matrix A following the formula

A = L*Lt 

where :
- **L** is a lower triangular matrix with positive diagonal entries  
- Lt is the transpose of **L**


**Properties**  
- Only works for **symmetric, square ,positive-definite** matrices  
- More efficient than LU decomposition for this case  
- Useful in solving systems of linear equations, Monte Carlo simulations, and optimization

**It is particularly useful for:**  
- Solving linear systems in the least squares sense (e.g., linear regression)  
- Optimization and simulation algorithms  

For symmetric and positive‑definite matrices, the Cholesky decomposition is roughly **twice as efficient** as LU decomposition.


In [6]:
# Define a symmetric, positive-definite matrix
A = np.array([[2, 1],
              [1, 1]])

# Perform Cholesky decomposition
L = np.linalg.cholesky(A)

# Print the lower triangular matrix L
print("Lower triangular matrix L:\n", L)

# Reconstruct the original matrix A using L · Lᵀ
A_reconstructed = L @ L.T
print("\nReconstructed matrix A (L · Lᵀ):\n", A_reconstructed)

Lower triangular matrix L:
 [[1.41421356 0.        ]
 [0.70710678 0.70710678]]

Reconstructed matrix A (L · Lᵀ):
 [[2. 1.]
 [1. 1.]]
