# Creating fixed Data arrays , matrices and tensors 

Using numpy we can create fixed data arrays frequently needed in various scenarios or just if you do not want to create an example manually:

#   -How create a matrix filled with zeroes

In [1]:
import numpy as np

matrix_zeroes = np.zeros((2,4), dtype=np.float32)
print(matrix_zeroes)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]


##   -How crate an N-dimension array filled with ones

In [2]:
tensor_ones = np.ones((2,2,2), dtype=np.int8)
print(tensor_ones)

[[[1 1]
  [1 1]]

 [[1 1]
  [1 1]]]


##  - How create a N-dimensional empty array filled with random garbage placeholder elements

In [4]:
empty_tensor = np.empty((2,3,2), dtype=str)
print(empty_tensor)

[[['' '']
  ['' '']
  ['' '']]

 [['' '']
  ['' '']
  ['' '']]]


## -How create an array made of a simple list of nubers

In [8]:
arange_arr = np.arange(0, 11, 2, dtype=np.double) # arange take as arguments start stop step like slicing and eventually dtype
print(arange_arr)

[ 0.  2.  4.  6.  8. 10.]


## - Create an array of numers equally spaced in a certain range between two values

In [20]:
linspaced_arr = np.linspace(0,9,num=10, dtype=float)  # linspace takes as arguments(startnumb , stopnumb , num= number_of_separator_numbers_between_start_and_stop)
print(linspaced_arr)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
