# Basic Operations with Arrays 
We can perform a various range of operations on the arrays to modify them, in this notepad we will explore:
- sorting with np.sort(arrayname)
- Reshaping trought the .reshape() method 
- Concatenation with np.concatenate()
- Reshape with .reshape()
- Adding dimensions with .expand_dims()
- Splitting an array in smaller arrays being allowed how and where to split them using split()
- Stacking arrays in a new dimension using .stack()
- Flattening an array with the method .flatten()

In [2]:
# Examples Array Creation
import numpy as np 

arr = np.array([33,44,55,6,7,21,8])
matr = np.array([[77,99,100], [34, 44, 87], [102,45,88]])
print("Example array : " ,arr )
print("\nExample matrix :\n", matr)

Example array :  [33 44 55  6  7 21  8]

Example matrix :
 [[ 77  99 100]
 [ 34  44  87]
 [102  45  88]]


## Sorting Arrays

Wa can change the order of an array trought sorting following our needs

In [3]:
sorted_arr = np.sort(arr, kind= "mergesort") # with kind we can select the sorting algoritm (each with perks and )
print("\nSorted array : \n", sorted_arr)
sorted_matrix = np.sort(matr, axis= 1) # the parameter axis allows us to select in wich axis we want to sort
print("\nSorted matrix : \n", sorted_matrix)


Sorted array : 
 [ 6  7  8 21 33 44 55]

Sorted matrix : 
 [[ 77  99 100]
 [ 34  44  87]
 [ 45  88 102]]


## Concatenations of arrays

We can concatenate arrays in a new array also specifying by what axis, concatenation does not add new dimensions like instead does stacking; it just merge everything in an existing dimension for example [1,2,3] +[1,2,3] = [1,2,3,1,2,3].

In [4]:
doublearray = np.concatenate([arr, arr]) 
print("Array Concatenated with itself : ", doublearray) # The number of dimensions stay invariated
matr_concaty = np.concatenate([matr, matr], axis=0)
matr_concatx = np.concatenate([matr,matr], axis=1)
print("\nMatrix Concatenated with itself by y axis : \n", matr_concaty) #here concatenation happens in the row dimension visually the "Y"
print("\nMatrix Concatenated with itself by x axis : \n", matr_concatx) #here concatenation happens in the row dimension visually the "X"

Array Concatenated with itself :  [33 44 55  6  7 21  8 33 44 55  6  7 21  8]

Matrix Concatenated with itself by y axis : 
 [[ 77  99 100]
 [ 34  44  87]
 [102  45  88]
 [ 77  99 100]
 [ 34  44  87]
 [102  45  88]]

Matrix Concatenated with itself by x axis : 
 [[ 77  99 100  77  99 100]
 [ 34  44  87  34  44  87]
 [102  45  88 102  45  88]]


## Reshaping of an array

We can reshape an array to rearrange it's dimensions, but with a limit : TOTAL SIZE CAN NOT CHANGE 

In [5]:
matrix_random = np.ones((4,4))
print("\nMatrix before reshaping (4 by 4) :\n",matrix_random)
matrix_reshaped = matrix_random.reshape(2,2,2,2)
print("\nMatrix reshaped to (2,2,2,2) : \n", matrix_reshaped)
print(f"\nOld number of dimensions : {matrix_random.ndim} New number od dimensions : {matrix_reshaped.ndim}") # NEW Dimensions were added
print(f"\nOld shape : {matrix_random.shape} New Shape : {matrix_reshaped.shape}") # shapes have been modifyed
print(f"\nOld shape : {matrix_random.size} New Shape : {matrix_reshaped.size}") # total size is unchanged and cannot change and can not be different


Matrix before reshaping (4 by 4) :
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

Matrix reshaped to (2,2,2,2) : 
 [[[[1. 1.]
   [1. 1.]]

  [[1. 1.]
   [1. 1.]]]


 [[[1. 1.]
   [1. 1.]]

  [[1. 1.]
   [1. 1.]]]]

Old number of dimensions : 2 New number od dimensions : 4

Old shape : (4, 4) New Shape : (2, 2, 2, 2)

Old shape : 16 New Shape : 16


## Adding New Axis to an array

We can add a new dimension or more than one

In [6]:
new_dim_arr= np.expand_dims(arr, axis=[1,2]) # we can add dimensions with an iterable for multipe dimension and the parameter axis=
print(new_dim_arr, new_dim_arr.shape)

[[[33]]

 [[44]]

 [[55]]

 [[ 6]]

 [[ 7]]

 [[21]]

 [[ 8]]] (7, 1, 1)


## Stacking arrays

Stacking arrays on a new dimension 

In [7]:
stacked_arrays = np.stack([arr,arr,arr])
print("Stacked_arrays : ", stacked_arrays)

stacked_matrix_x = np.stack([matr], axis= 1)
stacked_matrix_y = np.stack([matr], axis=0)
print("\n", stacked_matrix_x, stacked_matrix_x.shape)
print("\n", stacked_matrix_y, stacked_matrix_y.shape)


Stacked_arrays :  [[33 44 55  6  7 21  8]
 [33 44 55  6  7 21  8]
 [33 44 55  6  7 21  8]]

 [[[ 77  99 100]]

 [[ 34  44  87]]

 [[102  45  88]]] (3, 1, 3)

 [[[ 77  99 100]
  [ 34  44  87]
  [102  45  88]]] (1, 3, 3)


## Splitting Arrays

In [8]:
splitted_matrix = np.split(matr, 3, axis=1) # splitting the 3 by 3 matrix by columns in 3 equal parts
print("Splitted Maxtrix by y : " , splitted_matrix)

uevenly_splitted_arrays = np.array_split(arr, 5) # splitting in 5 arrays not necessarly equal
print("Unevenly splitted Arrays : " , uevenly_splitted_arrays)

chosen_splitted_arr = np.split(arr, [1,2,4,5]) #by adding indexes inside square bracket we can specify where we want the array to be splitted
print("\nChosen array_split : ", chosen_splitted_arr)



Splitted Maxtrix by y :  [array([[ 77],
       [ 34],
       [102]]), array([[99],
       [44],
       [45]]), array([[100],
       [ 87],
       [ 88]])]
Unevenly splitted Arrays :  [array([33, 44]), array([55,  6]), array([7]), array([21]), array([8])]

Chosen array_split :  [array([33]), array([44]), array([55,  6]), array([7]), array([21,  8])]


## Flattening of a multi dimensional array 

This method helps us to simplify a complex shaped array in one dimension.

In [9]:
flattened_array = matr.flatten()
print("Flattened Array : ", flattened_array)

Flattened Array :  [ 77  99 100  34  44  87 102  45  88]
