# Operazions between vectors 

In this lesson we will study different operations between arrays in this context called vectors, they follow using vectorial math.
They have to follow some basic rules that do not really change when adding dimension.
These are :
- Shape Compatibility Arrays must have compatible shapes. If shapes differ, NumPy applies broadcasting rules to try to align them; warning: you can not broadcast everything into a conpatible vector; we will see broadcasting later in the next lesson.
- Element-wise Logic Operations are applied to corresponding elements across arrays.
- Adding dimensions (going from 1D to 2D or 3D) doesn’t change the logic

In [ ]:
# Creating test Datas
# Vectors MUST have the same shape to be operated, or a shape that can be broadcasted into a vector compatible with the other vector
import numpy as np
vec1 = np.array([2,3,4,5,6])
vec2 = np.array([22,33,44,55,66])

## Adding two vectors

In [3]:
sum_of_vectors = vec1 + vec2 # very intuitive
print("Sum of the two vectors : ", sum_of_vectors)

Sum of the two vectors :  [24 36 48 60 72]


## Difference of two vectors 

In [4]:
difference_of_vectors = vec2 - vec1
print("Difference of the two vectors v2 - v1: ", difference_of_vectors )

Difference of the two vectors v2 - v1:  [20 30 40 50 60]


# Moltiplication between vectors 

In [5]:
moltiplication_of_vectors = vec1 * vec2
print(moltiplication_of_vectors)

[ 44  99 176 275 396]


## Division Between Vectors 

In [6]:
division_of_vectors = vec2 // vec1 # we can use / or // to get as usual the rounded integer or the decimal float
print(division_of_vectors)

[11 11 11 11 11]


## Operations between vectors and scalar 

This kind of operations are allowed by the broadcasting rules that allows this operation.

In [7]:
vec_add_scalar = vec2 +11
vec_diff_scalar = vec2 -11
vec_molt_scalar = vec2 * 11
vec_div_scalar = vec2 // 11



print("Addition (vec2 + 11):", vec_add_scalar)
print("Subtraction (vec2 - 11):", vec_diff_scalar)
print("Multiplication (vec2 * 11):", vec_molt_scalar)
print("Integer Division (vec2 // 11):", vec_div_scalar)

Addition (vec2 + 11): [33 44 55 66 77]
Subtraction (vec2 - 11): [11 22 33 44 55]
Multiplication (vec2 * 11): [242 363 484 605 726]
Integer Division (vec2 // 11): [2 3 4 5 6]


## Array Compatibility and Broadcasting

Broadcasting is NumPy’s mechanism for performing operations between arrays of different shapes. It allows smaller arrays to be automatically expanded to match the shape of larger ones — without copying data — enabling fast and memory-efficient computations.

    -> Example to explain the basic concept : arr_1 = 9; + arr_2 = (3,3,3)
    -> Arr_1_broadcasted : Arr_1_broadcasted = 9,9,9 x 3,3,3(arr_2) = 27, 27 ,27

## When two array are broadcast compatible?
To determine if two arrays are broadcast-compatible, align the entries of their shapes such that their trailing dimensions are aligned, and then check that each pair of aligned dimensions satisfy at least one of the following rules:
-  The aligned dimensions have the same size
-  One of the dimensions has a size of 1

Let's see an example!

arr1.shape = 10 88 77 29

arr2.shape = __ 88 1  1 

---They are compatible!---

##### Let's see a code example :

     

In [14]:
arr1 = np.ones((3, 14, 7, 1))

arr2 = np.ones((14, 1, 1))

# Broadcasted addition
arr_result = arr1 + arr2 


print("arr1.shape:", arr1.shape)
print("arr2.shape:", arr2.shape)
print("result.shape:", arr_result.shape)

arr1.shape: (3, 14, 7, 1)
arr2.shape: (14, 1, 1)
result.shape: (3, 14, 7, 1)


In [ ]:
list_3d = [
    [
    [1,2,4],
    [1,2,3],
    [1,2,3],
    ],
    [
    [1,2,3],
    [1,2,3],
    [1,2,10],
    ],
    [
    [3,2,3],
    [1,2,3],
    [2,2,3],
    ]
] 

array_3d = np.array(list_3d)

# Executing aggregation functions on the array or parts of it 

In [ ]:
# Sum across axis=2 (columns)
sum_axis2 = array_3d.sum(axis=2)
print(f"\n📐 Sum across axis=2 (columns → each row becomes a single number):")
print(sum_axis2)

# Sum across axis=1 (rows)
sum_axis1 = array_3d.sum(axis=1)
print(f"\n📏 Sum across axis=1 (rows → each block becomes a single row):")
print(sum_axis1)

# Sum across axis=0 (blocks)
sum_axis0 = array_3d.sum(axis=0)
print(f"\n📊 Sum across axis=0 (blocks → same positions across blocks are added):")
print(sum_axis0)


🔷 Original array (shape (3, 3, 3)):


📐 Sum across axis=2 (columns → each row becomes a single number):
[[ 7  6  6]
 [ 6  6 13]
 [ 8  6  7]]

📏 Sum across axis=1 (rows → each block becomes a single row):
[[ 3  6 10]
 [ 3  6 16]
 [ 6  6  9]]

📊 Sum across axis=0 (blocks → same positions across blocks are added):
[[ 5  6 10]
 [ 3  6  9]
 [ 4  6 16]]
