## Operations Beween Matrices

Now let's see operation between matrices is more or less the same as the operations with the vectors for addiction and subtraction and a bit different for moltiplication and division, sice in this case the two last operation do not get operated in the exact same way, but each element is operated in the opposite dimension, each element in the result is computed as the dot product of a row Matrix A and a column from matrix B. For example x 2 gets multiplied with y 2 of the other matrix.
IMPORTANT NOTE MATRICES MOLTIPLICATION DOES NOT BROADCAST.
But let's start from the basics, addiction and subtraction.


#### As always let's create sample datas

In [28]:
import numpy as np

A = np.array([[1, 2, 22],
              [3, 4, 78]])

B = np.array([[12, 21],
              [30, 48],
              [21,32]])

C = np.array([[10,10,22],
             [33,55,22]])

D =  np.array([2,3,4])

# Addiction

There are not many differencenses between vectors and matrices or tensors in this context the shape of de two array/vectors must concide!

In [29]:
ac_addicition = A + C
print("Matrix A + Matrix C =\n", ac_addicition )

Matrix A + Matrix C =
 [[ 11  12  44]
 [ 36  59 100]]


# Subtraction

Same

In [30]:
cd_subtraction = C - D # CD shapes are differents but as you can see the broadcasting work effortless
print("Matrix C - Matrix D =\n", ac_addicition)

Matrix C - Matrix D =
 [[ 11  12  44]
 [ 36  59 100]]


## Moltiplication

We have multiple ways to moltiplicate two matrices or tensors:
- The * operator performs element-by-element multiplication. This means that each element in one array is multiplied directly by the corresponding element in another array. This operation requires that the arrays have the same shape, or that one can be broadcast to match the other.

- The @ operator in Python is used for matrix multiplication, and in NumPy it behaves according to the rules of linear algebra. Unlike the * operator, which multiplies arrays element by element, @ performs a structured operation that combines rows and columns to produce a new matrix. This operation is only valid if the **number of columns in A matches the number of rows in B**. That’s the key rule of matrix multiplication.

In [31]:
ab_moltiplication_inv = A @ B  # inverted moltiplication
print("Matrix A * Matrix B  inverted =\n", ab_moltiplication_inv)

ac_moltiplicazion_lin = A * C # straight element wise operations
print("\nMatrix A * Matrix B  linear =\n", ac_moltiplicazion_lin)


Matrix A * Matrix B  inverted =
 [[ 534  821]
 [1794 2751]]

Matrix A * Matrix B  linear =
 [[  10   20  484]
 [  99  220 1716]]


# Division 

In [34]:
ca_division_lin = C // A  # inverted moltiplication
print("Matrix A // Matrix B linear =\n", ca_division_lin)


Matrix A // Matrix B linear =
 [[10  5  1]
 [11 13  0]]


# 