# Types of matrices

In linear algebra there are several types of special matrices each one useful in different fields of the ai/machine_learning word

In [1]:
import numpy as np

## Square Matrices

A **square matrix** is one where the number of rows is equal to the number of columns:
This contrasts with a **rectangular matrix**, which has a different number of rows and columns.
When rows and columns are the same number the matrix will be called of the order of that number.

The elements located along the line from the top-left corner to the bottom-right corner form the **main diagonal**.

**Useful related Methods:**
- np.linalg.matrix_rank ---> useful to get the rank of the matrix

In [2]:
import numpy as np

# 1) Create a 3x3 square matrix (from a Python list of lists)
square_matrix = np.array([
    [2, 4, 0],
    [1, 3, 5],
    [7, 0, -1]
], dtype=float)

print("Square matrix :\n", square_matrix)
print("Rank of the matrix : ", np.linalg.matrix_rank(square_matrix))  # we use this method to get the rank of the matrix


Square matrix :
 [[ 2.  4.  0.]
 [ 1.  3.  5.]
 [ 7.  0. -1.]]
Rank of the matrix :  3


## 🔁 Symmetric Matrices

A **symmetric matrix** is a special type of square matrix in which the upper triangular part is equal to the lower triangular part.

- The axis of symmetry is always the **main diagonal**, which runs from the top-left corner to the bottom-right corner.
- This means that the element at position (i , y) is equal to the element at position (j, i) for all valid indices.
- Some matrices can be symmetric but not square for exaple a rectangular matrix can still be simmetric

In [4]:
import numpy as np

symmetric_matrix_square = np.array([
    [3, 3, 3],
    [3, 3, 3],
    [3, 3, 3]
])

symmetric_matrix_rectang = np.array([
    [3, 3, 3, 3],
    [3, 3, 3, 3],
    [3, 3, 3, 3],
    [3, 3, 3, 3]
])

print("Symmetric Square matrix:\n", symmetric_matrix_square)
print("\nSymmetric Rectangular matrix:\n", symmetric_matrix_rectang)

Symmetric Square matrix:
 [[3 3 3]
 [3 3 3]
 [3 3 3]]

Symmetric Rectangular matrix:
 [[3 3 3 3]
 [3 3 3 3]
 [3 3 3 3]
 [3 3 3 3]]


## 🔺 Triangular Matrices

A **triangular matrix** is a special kind of square matrix in which either all elements **above** or **below** the main diagonal are zero.

- If all values **below the main diagonal** are zero, it's called an **upper triangular matrix**.
- If all values **above the main diagonal** are zero, it's called a **lower triangular matrix**.

**--Methods useful for triangular matrices--**
- np.tril() → for obtaining lower triangular matrix
- np.triu() → for obtaining upper triangular matrix

In [6]:
# Lower triangular
triangular_matrix_square_lower = np.array([
    [3, 0, 0],
    [3, 3, 0],
    [3, 3, 3]
])
print("Lower triangular (square):\n", triangular_matrix_square_lower)

# Upper triangular
triangular_matrix_square_upper = np.array([
    [3, 3, 3],
    [0, 3, 3],
    [0, 0, 3]
])
print("\nUpper triangular (square):\n", triangular_matrix_square_upper)

Lower triangular (square):
 [[3 0 0]
 [3 3 0]
 [3 3 3]]

Upper triangular (square):
 [[3 3 3]
 [0 3 3]
 [0 0 3]]


## 📊 Diagonal Matrices

A **diagonal matrix** is one in which all values outside the **main diagonal** are equal to zero.

- It is often represented by the letter **D**.
- A diagonal matrix can be described either as a full matrix or as a **vector containing just the diagonal elements**.

Although diagonal matrices are typically square, it's also possible to define a **diagonal rectangular matrix**, in which the diagonal extends only as far as the **smallest dimension**.


In [ ]:
# Square diagonal matrix
diagonal_matrix_square = np.diag([3, 3, 3])

print("Diagonal matrix (square and symmetric):\n", diagonal_matrix_square)

Diagonal matrix (square):
 [[3 0 0]
 [0 3 0]
 [0 0 3]]


## 🧩 Identity Matrix

The **identity matrix** is commonly denoted by the letter **I** and has the following features:
- All elements along the **main diagonal** are equal to **one**.
- All other elements in the matrix are equal to **zero**.
- When multiplied by another compatible matrix, it **does not alter its value**.

In [8]:
import numpy as np

# Square identity matrix (standard)
identity_matrix_square = np.identity(3, dtype=int)


print("Identity matrix (square):\n", identity_matrix_square)

Identity matrix (square):
 [[1 0 0]
 [0 1 0]
 [0 0 1]]
