# Operations on Matrixs

We can do ton of operations on maxtrix very useful into the data manipulation.
As always let's start with the creation of some sample datas.

In [1]:
import numpy as np 

matrix = [
    [22,33,44],
    [100,99,55],
    [66,77,88]
]

array_matrix = np.array(matrix)

# Moltipling a Matrix for a scalar

As for vectors we can do this operation to multiply each element for a certain amount.

In [2]:
matrix_for_scalar = array_matrix * 3
print("Matrix multiplied by a scalar three :\n", matrix_for_scalar)

Matrix multiplied by a scalar three :
 [[ 66  99 132]
 [300 297 165]
 [198 231 264]]


## 📘 Matrix Algebra: Transposition

A defined matrix can be **transposed**, resulting in a new matrix where rows and columns are swapped . Transposition is indicated with a  **T** next to the matrix name:  
**C = Aᵀ**

A transposed matrix is obtained by transforming each row into a column.  
Given a matrix **A** with *m* rows and *n* columns (*m × n*),  
the transposed matrix **Aᵀ** will have *n* rows and *m* columns (*n × m*) 🧮.

In [3]:
transposed_matrix = matrix_for_scalar.T  # T is the method to transpose a matrix
print("Matrix Transposed :\n", transposed_matrix)  

Matrix Transposed :
 [[ 66 300 198]
 [ 99 297 231]
 [132 165 264]]


## 🔄 Matrix Algebra: Inversion

Matrix inversion is the operation that finds another matrix which, when multiplied by the original one, yields the identity matrix 🎯.  
Given a matrix **A**, we look for a matrix **B** such that:  
**A • B = B • A = Iₙ**

The inverse of **A** is denoted with the superscript **−1**:  
**B = A⁻¹**

A matrix is **invertible** if there exists another matrix that, when multiplied by it, results in the identity matrix.  
⚠️ Not all matrices are invertible: a non-invertible square matrix is called **singular**.

In practice, inversion is not calculated "directly" but rather estimated through efficient numerical methods,  
often based on matrix **decompositions** like LU or QR 📐.

In [5]:
inv_matr = np.linalg.inv(transposed_matrix)
print("Matrix Inverted :\n", inv_matr)  

Matrix Inverted :
 [[-0.07170543  0.08280479 -0.01867512]
 [-0.00775194  0.01550388 -0.00775194]
 [ 0.04069767 -0.05109232  0.0179704 ]]


## 📏 Matrix Algebra: Matrix Trace

The **trace** of a square matrix is the sum of the elements on its **main diagonal**  
(from the top-left corner to the bottom-right corner).  

In NumPy, we can calculate the trace of a square matrix using the function:  
**`np.trace()`** 🧮

In [6]:
print("Trace of the matrix(array_matrix) =", np.trace(array_matrix))

Trace of the matrix(array_matrix) = 209
